SELECT
	(TO_TIMESTAMP(m.time_/1000))::date as _date,
	count(t.tx_type) as TotalTransactions,
	sum(case when t.tx_type = 'ChannelCloseMutualTx' then 1 else 0 end) as ChannelCloseMutualTx,
	sum(case when t.tx_type = 'ChannelCloseSoloTx' then 1 else 0 end) as ChannelCloseSoloTx,
	sum(case when t.tx_type = 'ChannelCreateTx' then 1 else 0 end) as ChannelCreateTx,
	sum(case when t.tx_type = 'ChannelDepositTx' then 1 else 0 end) as ChannelDepositTx,
	sum(case when t.tx_type = 'ChannelForceProgressTx' then 1 else 0 end) as ChannelForceProgressTx,
	sum(case when t.tx_type = 'ChannelSettleTx' then 1 else 0 end) as ChannelSettleTx,
	sum(case when t.tx_type = 'ChannelSlashTx' then 1 else 0 end) as ChannelSlashTx,
	sum(case when t.tx_type = 'ChannelSnapshotSoloTx' then 1 else 0 end) as ChannelSnapshotSoloTx,
	sum(case when t.tx_type = 'ChannelWithdrawTx' then 1 else 0 end) as ChannelWithdrawTx,
	sum(case when t.tx_type = 'ContractCallTx' then 1 else 0 end) as ContractCallTx,
	sum(case when t.tx_type = 'ContractCreateTx' then 1 else 0 end) as ContractCreateTx,
	sum(case when t.tx_type = 'NameClaimTx' then 1 else 0 end) as NameClaimTx,
	sum(case when t.tx_type = 'NamePreclaimTx' then 1 else 0 end) as NamePreclaimTx,
	sum(case when t.tx_type = 'NameRevokeTx' then 1 else 0 end) as NameRevokeTx,
	sum(case when t.tx_type = 'NameTransferTx' then 1 else 0 end) as NameTransferTx,
	sum(case when t.tx_type = 'NameUpdateTx' then 1 else 0 end) as NameUpdateTx,
	sum(case when t.tx_type = 'OracleExtendTx' then 1 else 0 end) as OracleExtendTx,
	sum(case when t.tx_type = 'OracleQueryTx' then 1 else 0 end) as OracleQueryTx,
	sum(case when t.tx_type = 'OracleRegisterTx' then 1 else 0 end) as OracleRegisterTx,
	sum(case when t.tx_type = 'OracleResponseTx' then 1 else 0 end) as OracleResponseTx,
	sum(case when t.tx_type = 'SpendTx' then 1 else 0 end) as SpendTx,
	sum(case when t.tx_type = 'SpendTx' then cast(t.tx->>'amount' as numeric(30,0)) else 0 end) as TotalSpend
from transactions t, micro_blocks m where t.micro_block_id=m.id group by  _date order by _date;
